name: bashellit
base: core22
version: '2.0.0'
summary: A minimal and clean editor for Bash scripts.
description: |
  Bashellit is a lightweight, focused editor designed specifically for writing 
  Bash scripts on Linux. Built for developers who find full-scale IDEs too
  bloated for simple shell scripting, it provides a clean and very minimalist environment.
  With Bashellit all your scrips are stored locally in the same place so you do not have to navigate to each script individually.

grade: stable
confinement: strict

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  bashellit:
    command: usr/bin/bashellit
    desktop: usr/share/applications/bashellit.desktop
    extensions: [ gnome ]
    environment:
      GDK_GL: disable

package-repositories:
  - type: apt
    components: [ main ]
    suites: [ noble ]
    key-id: 78E1918602959B9C59103100F1831DDAFC42E99D
    url: http://ppa.launchpad.net/snappy-dev/snapcraft-daily/ubuntu

parts:
  build-app:
    plugin: dump
    build-snaps:
      - node/20/stable
      - rustup/latest/stable
    build-packages:
      - libwebkit2gtk-4.1-dev
      - build-essential
      - curl
      - wget
      - file
      - libxdo-dev
      - libssl-dev
      - libayatana-appindicator3-dev
      - librsvg2-dev
      - dpkg
      - xdg-utils
    stage-packages:
      - libwebkit2gtk-4.1-0
      - libayatana-appindicator3-1
    source: .

    override-build: |
      set -eu
      export PATH="$HOME/.cargo/bin:$PATH"
    
      cargo install dioxus-cli --locked
      cargo build --release
      dx bundle --desktop --release
    
      BUNDLE_DIR=target/dx/bashellit/bundle/linux/bundle/deb
      DEB=Bashellit_0.1.0_amd64.deb
    
      # Extract the deb
      dpkg-deb -x $BUNDLE_DIR/$DEB extracted
    
      # Install binary
      install -Dm755 extracted/usr/bin/bashellit \
        $SNAPCRAFT_PART_INSTALL/usr/bin/bashellit
    
      # Install desktop file
      install -Dm644 extracted/usr/share/applications/Bashellit.desktop \
        $SNAPCRAFT_PART_INSTALL/usr/share/applications/bashellit.desktop
    
      # Install icons
      cp -r extracted/usr/share/icons \
        $SNAPCRAFT_PART_INSTALL/usr/share/